config/routes.rb
# For details on the DSL available within this file
# http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  # Authentication
  get "sign_in", to: "sessions#new", as: "sign_in"
  get "sign_up", to: "users#new", as: "sign_up"
  get "sign_out", to: "sessions#destroy", as: "sign_out"

  get "welcome", to: "welcome#show"

  resources :sessions, only: [:create, :delete]
  resources :users, only: [:create]
  resources :tenants, only: [:index]
  resources :ideas

  # constraints subdomain: "administration" do
  #   scope module: "administration" do
  #     match "organisation_sign_in/:id" => "organisation_sign_in#{create}",
  #           via: [:post],
  #           as: :administration_organisation_sign_in
  #     match "current_tenant/:id" => "current_tenant#create",
  #           via: [:post],
  #           as: :administration_current_tenant
  #   end
  # end

  get "", to: "tenants#index", constraints: { subdomain: /.+/ }

  root "welcome#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord  
  validates :name, :description, presence: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # attr_accessor :password

  # Add methods to set and authenticate against a BCrypt password
  # http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
  has_secure_password
  # password_digest attribute added to User model
  # user = User.create(password: '', password_confirmation: '')
  # user.authenticate('valid_password')

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            on: :create

  # has_secure_password replaces all of this:
  # before_save :encrypt_password
  #
  # validates :password, confirmation: true, presence: true
  #
  # def encrypt_password
  #   if password.present?
  #     self.password_salt = BCrypt::Engine.generate_salt
  #     self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  #   end
  # end

  def authenticated(password)
    authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_tenant

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_tenant
    Tenant.find_by(subdomain: request.subdomain)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, except: [:index, :new, :create]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = cell(:idea, collection: Idea.order(created_at: :desc))
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show; end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        IdeaBroadcastJob.perform_later(@idea)
        format.html { redirect_to(@idea, flash: { success: I18n.t(".success") }) }
      else
        format.html { render :new }
      end
    end
  end

  # GET /ideas/1/edit
  def edit; end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to(@idea, flash: { success: I18n.t(".success") }) }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to(ideas_url, flash: { success: I18n.t(".success") }) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def new
  end

  def create
    redirect_to sign_in_redirect, flash: sign_in_flash_message
  end

  def destroy
    session[:user_id] = nil
    redirect_to welcome_path, flash: {success: "Signed out!"}
  end

  private

  def session_params
    params.permit(:email, :password)
  end

  def authenticate_user
    # http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html

    @current_user ||= User.find_by_email(session_params[:email])&.
      authenticated(session_params[:password])
  end

  def sign_in_redirect
    set_session_user ?  ideas_path : welcome_path
  end

  def set_session_user
    return if @current_user.blank?
    session[:user_id] = @current_user.id
  end

  def sign_in_flash_message
    if session[:user_id].present?
      { success: "Signed in!" }
    else
      { error: "Invalid email or password!" }
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = Tenant.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to ideas_path, notice: "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/ideas/_form.html.haml
= form_for(idea) do |f|
  .form-group
    - if idea.errors.any?
      .alert.alert-warning#error_explanation
        %h2= pluralize(idea.errors.count, "error")
        prohibited this idea from being saved:

        %ul
        - idea.errors.full_messages.each do |message|
          %li= message

    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'

    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'

    .form-group
      = f.submit :class => 'btn btn-default' |
      .btn.btn-default= link_to 'Cancel', ideas_path

app/views/ideas/_idea.html.haml
= cell(:idea, idea).(:show)

app/views/ideas/edit.html.haml
%h1 Editing Idea
= render 'form', idea: @idea

app/views/ideas/index.html.haml
%h1 Experimental Ideas

%br
.btn.btn-default= link_to 'New Idea', new_idea_path
%br
%br

.ideas
  = @ideas

.btn.btn-default= link_to 'New Idea', new_idea_path

app/views/ideas/new.html.haml
%h1 New Idea
= render 'form', idea: @idea

app/views/ideas/show.html.haml
- if notice.present?
  %p.alert.alert-success#notice= notice

%h4= link_to @idea.name, edit_idea_path(@idea)

%p= @idea.description

.btn.btn-default= link_to 'New Idea', new_idea_path |
.btn.btn-default= link_to 'Back', ideas_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rails 5 Sandbox
    = csrf_meta_tags
    = action_cable_meta_tag
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render partial: "shared/navbar"
    = render partial: "shared/flash"
    .container= yield
    = render partial: "shared/footer"

app/views/shared/_flash.html.haml
- if flash.present?
  .container
    .alert.alert-block
      %button{ type: "button", class: "close", data: { dismiss: "alert" } } &times; &nbsp;
      - flash.each do |name, msg|
        .alert{ class: "alert-#{name}"}= msg

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %p.text-muted Sandbox™

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    <!-- Brand and toggle get grouped for better mobile display -->
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', 'aria-expanded' => false, :data => {'target' => '#bs-example-navbar-collapse-1', 'toggle' => 'collapse'}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("icons/logo.png", alt: "brand", class: "navbar-brand"), "https://github.com/RianaFerreira"

    <!-- Collect the nav links, forms, and other content for toggling -->
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      -if current_user
        %ul.nav.navbar-nav
          %li.active
            = link_to 'ideas', '/ideas'
            %span.sr-only(current)

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          = render partial: "shared/search"
          = render partial: "sessions/sign_out"
        - else
          = render partial: "sessions/sign_in"

app/views/shared/_search.html.haml
%form.navbar-form.navbar-left{"role" => "search"}
  .form-group
    = text_field_tag :query, params[:query], class: "form-control", placeholder: "Search"
  = submit_tag "Search", class: "btn btn-default"

app/views/tenants/index.html.haml
.jumbotron.text-center
  %h2.jumbotron-heading Application Tenants
  .lead.text-muted configuration details for each tenant

.row
  - @tenants.each do |tenant|
    .col-sm-6.col-md-4
      .card
        .card-body
          %h4.card-title= tenant.name
          %p.card-text
            %strong subdomain:
            = tenant.subdomain

app/views/users/new.html.haml
%h1 Sign Up

.form
  = form_for @user do |f|
    .form-group
      - if @user.errors.any?
        .error_messages
          %h2 Form is invalid
          %ul
            - for message in @user.errors.full_messages
              %li= message

    .form-group
      .form-control-label= f.label :email
      = f.text_field :email, class: "form-`control"

    .form-group
      .form-control-label= f.label :password
      = f.password_field :password, class: "form-control"

    .form-group
      .form-control-label= f.label :password_confirmation
      = f.password_field :password_confirmation, class: "form-control"

    .form-group
      .button= f.submit "Sign up"

app/views/welcome/show.html.haml
.jumbotron.jumbotron-fluid
  %h1 Explore programming concepts
  .lead Understand some patterns that solve problems often faced when building applications
  %strong Inspiration
  = link_to "Enhanced Rails Architecture", "https://github.com/CodeRocketCo/enhanced-rails-architecture"
  %hr.my-4

  .row
    .col-sm-6.col-md-4
      .card
        .card-body
          %h4.card-title Multi-Tenancy
          %p.card-text Custom scopes vs Apartment gem
          = link_to "Apartment", "https://github.com/influitive/apartment", class: "badge badge-light"
          = link_to "Custom scopes", "https://github.com/railscasts/388-multitenancy-with-scopes", class: "badge badge-light"

    .col-sm-6.col-md-4
      .card
        .card-body
          %h4.card-title Managing view helpers
          %p.card-text Decorator PORO vs Draper gem
          = link_to "Draper", "https://github.com/drapergem/draper", class: "badge badge-light"
          = link_to "Decorator PORO", "https://robots.thoughtbot.com/evaluating-alternative-decorator-implementations-in", class: "badge badge-light"

    .col-sm-6.col-md-4
      .card
        .card-body
          %h4.card-title File uploads
          %p.card-text ActiveStorage vs CarrierWave gem
          = link_to "ActiveStorage", "https://github.com/rails/rails/tree/master/activestorage", class: "badge badge-light"
          = link_to "CarrierWave", "https://github.com/carrierwaveuploader/carrierwave", class: "badge badge-light"
  %br

  .row
    .col-sm-6.col-md-4
      .card
        .card-body
          %h4.card-title Action Cable
          %p.card-text How to use Action Cable in Rails 5
          = link_to "Action Cable overview", "http://edgeguides.rubyonrails.org/action_cable_overview.html", class: "badge badge-light"
          = link_to "Action Cable examples", "https://github.com/rails/actioncable-examples", class: "badge badge-light"
          = link_to "Avoid channel name collisions", "https://redis.io/topics/pubsub#database-amp-scoping", class: "badge badge-light"
          = link_to "Action Cable Devise auth", "https://rubytutorial.io/actioncable-devise-authentication/", class: "badge badge-light"